### ISSUE TITLE
[Feat] 홈 UI 구현

### ISSUE THREAD

**Issue by chae-young** [FreshManProject/FreshMan-Frontend#39]
## 설명
홈 UI 를 구현합니다

## Todo

- [x] 홈 UI
- [x] 홈 페이지 라우터 구성
- [x] 가로 스크롤 구현 (스로틀 처리)
- [x] 리스트 더미 데이터 연동 처리
