### ISSUE TITLE
[Feat] 검색 기능 수정

### ISSUE THREAD

**Issue by chae-young** [FreshManProject/FreshMan-Frontend#50]
## 설명
검색 페이지 & 기능 최근검색어를 수정 및 구현

## Todo

- [x] 검색 페이지 UI 수정
- [x] 최근 검색어 기능 추가 (삭제)
- [x] 검색 mock API 연동 리팩 필요
- [x] 검색 결과 페이지 연동
